CREATE TABLE EMPLOYEE (
EMPID NUMBER NOT NULL,
USERNAME NUMBER (8) UNIQUE NOT NULL,
PASSWORD NUMBER (8) NOT NULL,
FIRSTNAME VARCHAR (20) NOT NULL,
LASTNAME VARCHAR (20) NOT NULL,
SPECIALITY VARCHAR (200) NOT NULL,
PRIMARY KEY (EMPID)
);

CREATE TABLE CLIENT(
CLIENTID NUMBER NOT NULL,
EMPID NUMBER NOT NULL,
CUSTOMERLASTNAME VARCHAR2 (20) NOT NULL,
ROAD VARCHAR2(20) NOT NULL,
ADDRESS NUMBER NOT NULL,
CITY VARCHAR2(20) NOT NULL,
TK NUMBER NOT NULL,
PRIMARY KEY (CLIENTID),
FOREIGN KEY (EMPID) REFERENCES  EMPLOYEE(EMPID)
);

CREATE TABLE CUSTOMERPHONE(
CLIENTID NUMBER NOT NULL,
CUSTOMERPHONE NUMBER NOT NULL,
PRIMARY KEY (CLIENTID,CUSTOMERPHONE),
FOREIGN KEY(CLIENTID) REFERENCES CLIENT(CLIENTID)
);

CREATE TABLE ORDERS(
ORDERID NUMBER NOT NULL,
SELLERID NUMBER NOT NULL,
CLIENTID NUMBER,
PRODUCTNAME VARCHAR2(50) NOT NULL,
QUANTITY NUMBER NOT NULL,
ORDERSUM NUMBER,
PRIMARY KEY(ORDERID,PRODUCTNAME),
FOREIGN KEY(CLIENTID) REFERENCES CLIENT(CLIENTID),
FOREIGN KEY(SELLERID) REFERENCES EMPLOYEE(EMPID)
);

CREATE TABLE PRODUCT(
PRODUCTID NUMBER NOT NULL,
NAME VARCHAR2(20) UNIQUE NOT NULL,
QUANTITY NUMBER NOT NULL,
QUALITY VARCHAR2(200) NOT NULL,
PRICE NUMBER NOT NULL,
SELLPRICE NUMBER NOT NULL,
EXPIREDATE DATE NOT NULL,
SUPPLIER VARCHAR2 (30) NOT NULL,
PRIMARY KEY (PRODUCTID)
);

CREATE TABLE CONTAINS(
PRODUCTID NUMBER NOT NULL,
ORDERID NUMBER NOT NULL,
PRODUCTNAME VARCHAR2(50) NOT NULL,
PRIMARY KEY(PRODUCTID, ORDERID,PRODUCTNAME),
FOREIGN KEY(ORDERID,PRODUCTNAME) REFERENCES ORDERS(ORDERID,PRODUCTNAME),
FOREIGN KEY(PRODUCTID) REFERENCES PRODUCT(PRODUCTID)
);

INSERT INTO EMPLOYEE(EMPID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, SPECIALITY)
VALUES (2, 10, 1234, 'Ashley', 'Bedene', 'Αποθηκάριος')

/*
DROP TABLE CONTAINS;
DROP TABLE CUSTOMERPHONE;
DROP TABLE ORDERS;
DROP TABLE PRODUCT;
DROP TABLE CLIENT;
DROP TABLE EMPLOYEE;
*/

